
    
# Use root/example as user/password credentials
version: '3.3'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: empdata
    volumes:
        - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080

volumes:
  db_data: